"""Secure credential management — password hashing, generation, and secret storage."""

from __future__ import annotations

import base64
import contextlib
import json
import os
import secrets
import string
import warnings
from typing import TYPE_CHECKING, Any

import bcrypt

from homehost.core.config import load_project_config, save_project_config

if TYPE_CHECKING:
    from pathlib import Path

# ── Password helpers ───────────────────────────────────────────────────────────


def hash_password(password: str) -> str:
    """Hash a password with bcrypt and return the hash string.

    Uses the default work factor (12 rounds) which provides a good
    balance between security and latency on modern hardware.

    Args:
        password: The plain-text password to hash.

    Returns:
        A bcrypt hash string (e.g. ``'$2b$12$...'``).
    """
    hashed: bytes = bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt())
    return hashed.decode("utf-8")


def verify_password(password: str, hash: str) -> bool:
    """Verify a plain-text password against a bcrypt hash.

    Args:
        password: The plain-text password to check.
        hash: The bcrypt hash string produced by :func:`hash_password`.

    Returns:
        ``True`` if the password matches the hash, ``False`` otherwise.
    """
    try:
        return bcrypt.checkpw(password.encode("utf-8"), hash.encode("utf-8"))
    except Exception:
        return False


# ── Password generation ────────────────────────────────────────────────────────

# Characters considered "safe" for passwords displayed in terminals and URLs
_PASSWORD_ALPHABET = string.ascii_letters + string.digits + "!@#$%^&*_=+"


def generate_strong_password(length: int = 16) -> str:
    """Generate a cryptographically random password.

    Uses :func:`secrets.choice` over a curated alphabet of letters, digits,
    and shell-safe punctuation.  The result is split into four equal segments
    separated by ``-`` for improved readability and copy-paste ergonomics.

    Args:
        length: Total number of characters (excluding separators).  Must be
            a positive multiple of 4; values that are not exact multiples are
            rounded up to the next multiple of 4.

    Returns:
        A password string formatted as ``'Xk9m-P2nQ-rT4w-Jv8s'``.

    Example::

        >>> pw = generate_strong_password(16)
        >>> len(pw.replace("-", "")) == 16
        True
    """
    # Round up to the nearest multiple of 4 so we can split evenly
    if length < 4:
        length = 4
    remainder = length % 4
    if remainder != 0:
        length += 4 - remainder

    chars = [secrets.choice(_PASSWORD_ALPHABET) for _ in range(length)]
    segment_size = length // 4
    segments = ["".join(chars[i * segment_size : (i + 1) * segment_size]) for i in range(4)]
    return "-".join(segments)


# ── Credential storage ─────────────────────────────────────────────────────────


def store_credential(project_name: str, username: str, password_hash: str) -> None:
    """Store credentials in the project's TOML config via the config system.

    Loads the existing project config for *project_name*, updates the
    ``security`` section with the supplied username and password hash, and
    writes it back atomically.

    Args:
        project_name: The registered HomeHost project name.
        username: The username to store.
        password_hash: The bcrypt hash of the password (from :func:`hash_password`).

    Raises:
        OSError: If the config file cannot be written.
    """
    cfg = load_project_config(project_name)
    cfg.security.basic_auth = True
    cfg.security.username = username
    cfg.security.password_hash = password_hash
    save_project_config(cfg)


# ── Caddy config generation ────────────────────────────────────────────────────


def generate_caddy_basicauth_block(username: str, password_hash: str) -> str:
    """Return a Caddy ``basicauth`` configuration block.

    Caddy's ``basicauth`` directive accepts bcrypt hashes directly.  The hash
    must start with ``$2b$`` (bcrypt) and be base64-encoded in Caddy's internal
    format.  For Caddy v2 the hash is used verbatim from ``caddy hash-password``.

    .. note::
        Hashes generated by HomeHost's :func:`hash_password` are standard
        bcrypt and are compatible with Caddy v2's ``basicauth`` directive.

    Args:
        username: The username to protect access with.
        password_hash: The bcrypt hash string.

    Returns:
        A multi-line Caddyfile ``basicauth`` block string.
    """
    if not username or not password_hash:
        return "# basicauth: no credentials configured"

    lines = [
        "basicauth /* {",
        f"    {username} {password_hash}",
        "}",
    ]
    return "\n".join(lines)


def format_credentials_display(username: str, password: str) -> str:
    """Return a formatted, human-readable credential display string for Rich console.

    Produces a Rich markup string with coloured labels suitable for printing
    via ``rich.print()`` or a Textual ``Label``.

    Args:
        username: The plain-text username.
        password: The plain-text password (shown once at generation time).

    Returns:
        A Rich-markup formatted string.

    Example output (Rich markup)::

        ┌─────────────────────────────────────┐
        │  Credentials for your project       │
        │                                     │
        │  Username : admin                   │
        │  Password : Xk9m-P2nQ-rT4w-Jv8s    │
        │                                     │
        │  Save these — the password cannot   │
        │  be recovered after this point.     │
        └─────────────────────────────────────┘
    """
    border = "─" * 41
    top = f"┌{border}┐"
    bot = f"└{border}┘"
    blank = f"│ {'':39} │"

    def row(label: str, value: str) -> str:
        content = f"  [bold]{label}[/bold] : [green]{value}[/green]"
        # Pad to fill the box width (content is Rich markup, measure raw chars)
        raw_len = len(label) + len(value) + 5  # "  label : value"
        padding = " " * max(0, 39 - raw_len)
        return f"│ {content}{padding} │"

    lines = [
        top,
        f"│ [bold yellow]  Credentials for your project[/bold yellow]{'':10} │",
        blank,
        row("Username", username),
        row("Password", password),
        blank,
        f"│ [dim]  Save these — the password cannot{'':2} [/dim] │",
        f"│ [dim]  be recovered after this point.{'':4} [/dim] │",
        bot,
    ]
    return "\n".join(lines)


# ── SecretStore ────────────────────────────────────────────────────────────────


class SecretStore:
    """Simple encrypted key-value store for secrets.

    Persists secrets in ``~/.homehost/secrets.json``.  If the
    ``cryptography`` package is installed, values are encrypted with Fernet
    (AES-128-CBC + HMAC-SHA256) using a machine-local key derived from a
    random 32-byte seed stored beside the store.  If ``cryptography`` is
    unavailable, values are stored with base64 obfuscation and a clear
    warning is emitted.

    The encryption key is stored in ``~/.homehost/secrets.key``.  This file
    should be protected with filesystem permissions (``0600``) — HomeHost sets
    this automatically.

    Usage::

        store = SecretStore()
        store.set("cloudflare_token", "abc123")
        token = store.get("cloudflare_token")
    """

    _KEY_FILE_NAME = "secrets.key"
    _STORE_FILE_NAME = "secrets.json"

    def __init__(self, store_path: Path | None = None) -> None:
        """Initialise the store.

        Args:
            store_path: Directory to use for the key and store files.
                Defaults to ``~/.homehost/``.
        """
        if store_path is None:
            from homehost.core.config import homehost_dir

            store_path = homehost_dir()

        self._dir = store_path
        self._dir.mkdir(parents=True, exist_ok=True)
        self._key_path = self._dir / self._KEY_FILE_NAME
        self._store_path = self._dir / self._STORE_FILE_NAME

        self._fernet: Any = None  # cryptography.fernet.Fernet instance or None
        self._use_fernet = self._init_fernet()

    # ── Encryption setup ───────────────────────────────────────────────────────

    def _init_fernet(self) -> bool:
        """Attempt to initialise Fernet encryption.  Returns True on success."""
        try:
            from cryptography.fernet import Fernet  # type: ignore[import]
        except ImportError:
            warnings.warn(
                "The 'cryptography' package is not installed. "
                "HomeHost secrets are stored with base64 obfuscation only — "
                "install 'cryptography' for proper encryption: pip install cryptography",
                stacklevel=3,
            )
            return False

        key_bytes = self._load_or_create_key()
        self._fernet = Fernet(key_bytes)
        return True

    def _load_or_create_key(self) -> bytes:
        """Load the Fernet key from disk, or generate and persist a new one."""
        from cryptography.fernet import Fernet  # type: ignore[import]

        if self._key_path.exists():
            raw = self._key_path.read_bytes().strip()
            # Validate that it's a proper Fernet key (44 base64 chars)
            if len(raw) == 44:
                return raw

        # Generate a fresh key
        key = Fernet.generate_key()
        # Write with restrictive permissions (owner read/write only)
        old_umask = os.umask(0o177)  # => mode 0o600
        try:
            self._key_path.write_bytes(key)
        finally:
            os.umask(old_umask)
        return key

    # ── Internal encode/decode ─────────────────────────────────────────────────

    def _encode(self, plaintext: str) -> str:
        """Encrypt or obfuscate a string value for storage."""
        raw = plaintext.encode("utf-8")
        if self._use_fernet and self._fernet is not None:
            return self._fernet.encrypt(raw).decode("ascii")
        # Fallback: base64 obfuscation
        return "b64:" + base64.b64encode(raw).decode("ascii")

    def _decode(self, stored: str) -> str:
        """Decrypt or de-obfuscate a stored value."""
        if stored.startswith("b64:"):
            return base64.b64decode(stored[4:]).decode("utf-8")
        if self._use_fernet and self._fernet is not None:
            return self._fernet.decrypt(stored.encode("ascii")).decode("utf-8")
        # Stored value appears to be Fernet-encrypted but Fernet is unavailable
        raise RuntimeError(
            "Secret is Fernet-encrypted but the 'cryptography' package is not installed. "
            "Install it with: pip install cryptography"
        )

    # ── Store I/O ──────────────────────────────────────────────────────────────

    def _load_store(self) -> dict[str, str]:
        """Read and parse the JSON store from disk."""
        if not self._store_path.exists():
            return {}
        try:
            data = json.loads(self._store_path.read_text(encoding="utf-8"))
            if isinstance(data, dict):
                return {str(k): str(v) for k, v in data.items()}
        except (json.JSONDecodeError, OSError):
            pass
        return {}

    def _save_store(self, data: dict[str, str]) -> None:
        """Atomically write the JSON store to disk with restrictive permissions."""
        import tempfile

        payload = json.dumps(data, indent=2, sort_keys=True).encode("utf-8")
        fd, tmp = tempfile.mkstemp(dir=self._dir, suffix=".tmp")
        try:
            os.write(fd, payload)
            os.close(fd)
            os.chmod(tmp, 0o600)
            os.replace(tmp, self._store_path)
        except Exception:
            with contextlib.suppress(OSError):
                os.unlink(tmp)
            raise

    # ── Public API ─────────────────────────────────────────────────────────────

    def set(self, key: str, value: str) -> None:
        """Store an encrypted secret under *key*.

        Args:
            key: Logical name for the secret (e.g. ``"cloudflare_token"``).
            value: The plain-text secret value to store.
        """
        if not key:
            raise ValueError("Secret key must not be empty.")
        store = self._load_store()
        store[key] = self._encode(value)
        self._save_store(store)

    def get(self, key: str, default: str = "") -> str:
        """Retrieve and decrypt a secret by key.

        Args:
            key: The key used when calling :meth:`set`.
            default: Value to return if the key does not exist.

        Returns:
            The decrypted secret, or *default* if not found.
        """
        store = self._load_store()
        encoded = store.get(key)
        if encoded is None:
            return default
        try:
            return self._decode(encoded)
        except Exception:
            return default

    def delete(self, key: str) -> bool:
        """Delete a secret by key.

        Args:
            key: The key to delete.

        Returns:
            ``True`` if the key existed and was deleted, ``False`` otherwise.
        """
        store = self._load_store()
        if key not in store:
            return False
        del store[key]
        self._save_store(store)
        return True

    def list_keys(self) -> list[str]:
        """Return a sorted list of all stored secret keys.

        Returns:
            Sorted list of key strings (values are not exposed).
        """
        return sorted(self._load_store().keys())
