"""FastAPI starter application — generated by HomeHost scaffold."""

from __future__ import annotations

import platform
import sys
from datetime import datetime
from typing import Annotated

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Application setup
# ---------------------------------------------------------------------------

app = FastAPI(
    title="HomeHost FastAPI App",
    description="A self-hosted FastAPI starter — served from your laptop via HomeHost.",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

# Allow requests from any origin so the browser preview works out of the box.
# Tighten this for production use.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Pydantic models
# ---------------------------------------------------------------------------


class HealthResponse(BaseModel):
    """Response schema for the /health endpoint."""

    status: str = Field(default="ok", description="Service health status.")
    timestamp: str = Field(description="ISO-8601 timestamp of the response.")
    python: str = Field(description="Python version string.")
    platform: str = Field(description="Host operating system.")
    version: str = Field(description="Application version.")


class ItemCreate(BaseModel):
    """Payload for creating a new item."""

    name: str = Field(..., min_length=1, max_length=120, description="Item name.")
    description: str = Field(default="", max_length=500, description="Optional description.")
    price: float = Field(..., gt=0, description="Price in USD (must be positive).")
    tags: list[str] = Field(default_factory=list, description="Arbitrary string tags.")


class Item(ItemCreate):
    """Full item representation including server-assigned fields."""

    id: int = Field(description="Unique item identifier.")
    created_at: str = Field(description="ISO-8601 creation timestamp.")


class ItemsResponse(BaseModel):
    items: list[Item]
    total: int


class EchoRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=1000)
    repeat: int = Field(default=1, ge=1, le=10)


class EchoResponse(BaseModel):
    original: str
    echoed: list[str]
    word_count: int


# ---------------------------------------------------------------------------
# In-memory data store (replace with a real DB in production)
# ---------------------------------------------------------------------------

_items: dict[int, Item] = {
    1: Item(
        id=1,
        name="Raspberry Pi 5",
        description="Great single-board computer for self-hosting.",
        price=80.0,
        tags=["hardware", "homelab"],
        created_at=datetime.now().isoformat(),
    ),
    2: Item(
        id=2,
        name="USB-C Power Bank",
        description="Keep your HomeHost server running during outages.",
        price=45.99,
        tags=["accessories"],
        created_at=datetime.now().isoformat(),
    ),
}
_next_id = 3

# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------


@app.get("/", response_class=HTMLResponse, include_in_schema=False)
async def root() -> str:
    """Serve a minimal HTML welcome page at the root."""
    return """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
  <title>HomeHost FastAPI App</title>
  <style>
    :root { --p:#6c63ff; --bg:#0d0d1a; --surface:#14142b; --text:#f0efff; --muted:#9ca3af; }
    *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
    body{font-family:"Inter",system-ui,sans-serif;background:var(--bg);color:var(--text);
         min-height:100vh;display:flex;flex-direction:column;align-items:center;
         justify-content:center;gap:1.5rem;padding:2rem;text-align:center}
    h1{font-size:2.5rem;font-weight:800;letter-spacing:-0.03em}
    .grad{background:linear-gradient(135deg,#6c63ff,#f59e0b);-webkit-background-clip:text;
          -webkit-text-fill-color:transparent;background-clip:text}
    p{color:var(--muted);max-width:480px;line-height:1.7}
    .links{display:flex;gap:1rem;flex-wrap:wrap;justify-content:center}
    a{padding:.55rem 1.2rem;border-radius:9999px;font-weight:600;font-size:.9rem;
      text-decoration:none;transition:transform 150ms,box-shadow 150ms}
    a:hover{transform:translateY(-2px)}
    .primary{background:var(--p);color:#fff}
    .ghost{border:2px solid #2d2b5a;color:var(--text)}
    code{font-family:monospace;background:#1e1b4b;padding:.15em .4em;border-radius:.3rem;font-size:.875em}
  </style>
</head>
<body>
  <h1>🏠 <span class="grad">FastAPI App</span></h1>
  <p>Your self-hosted FastAPI application is running.<br/>
     Browse the interactive API docs or explore the example endpoints below.</p>
  <div class="links">
    <a class="primary" href="/docs">Swagger UI →</a>
    <a class="ghost" href="/redoc">ReDoc →</a>
    <a class="ghost" href="/health">Health check</a>
    <a class="ghost" href="/items">Browse items</a>
  </div>
  <p style="font-size:.8rem">Edit <code>main.py</code> · changes reload automatically</p>
</body>
</html>"""


@app.get("/health", response_model=HealthResponse, tags=["System"])
async def health() -> HealthResponse:
    """Return application health status and runtime information."""
    return HealthResponse(
        status="ok",
        timestamp=datetime.now().isoformat(),
        python=sys.version.split()[0],
        platform=platform.system(),
        version=app.version,
    )


@app.get("/items", response_model=ItemsResponse, tags=["Items"])
async def list_items(
    tag: Annotated[str | None, Query(description="Filter items by tag.")] = None,
    limit: Annotated[int, Query(ge=1, le=100, description="Max results.")] = 20,
) -> ItemsResponse:
    """List all items, with optional tag filtering."""
    results = list(_items.values())
    if tag:
        results = [i for i in results if tag in i.tags]
    return ItemsResponse(items=results[:limit], total=len(results))


@app.get("/items/{item_id}", response_model=Item, tags=["Items"])
async def get_item(item_id: int) -> Item:
    """Retrieve a single item by ID."""
    if item_id not in _items:
        raise HTTPException(status_code=404, detail=f"Item {item_id} not found.")
    return _items[item_id]


@app.post("/items", response_model=Item, status_code=201, tags=["Items"])
async def create_item(payload: ItemCreate) -> Item:
    """Create a new item."""
    global _next_id
    item = Item(
        id=_next_id,
        created_at=datetime.now().isoformat(),
        **payload.model_dump(),
    )
    _items[_next_id] = item
    _next_id += 1
    return item


@app.delete("/items/{item_id}", status_code=204, tags=["Items"])
async def delete_item(item_id: int) -> None:
    """Delete an item by ID."""
    if item_id not in _items:
        raise HTTPException(status_code=404, detail=f"Item {item_id} not found.")
    del _items[item_id]


@app.post("/echo", response_model=EchoResponse, tags=["Utilities"])
async def echo(body: EchoRequest) -> EchoResponse:
    """Echo a message back, optionally repeated, with a word count."""
    echoed = [body.message] * body.repeat
    return EchoResponse(
        original=body.message,
        echoed=echoed,
        word_count=len(body.message.split()),
    )


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import uvicorn

    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
