"""Flask starter application — generated by HomeHost scaffold."""

from flask import Flask, jsonify, render_template

app = Flask(__name__)


@app.route("/")
def index():
    """Render the main landing page."""
    return render_template("index.html")


@app.route("/api/hello")
def hello():
    """Simple health-check / greeting endpoint."""
    return jsonify({"message": "Hello from HomeHost!", "version": "1.0"})


@app.route("/api/status")
def status():
    """Return application status."""
    import platform
    import sys

    return jsonify(
        {
            "status": "ok",
            "python": sys.version.split()[0],
            "platform": platform.system(),
        }
    )


if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=5000)
